### ISSUE TITLE
Possible attack vector when querying channels by connection

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/ibc-go#35]
According to silk node the query by [connectionChannels](https://github.com/dymensionxyz/ibc-go/blob/main-dym/modules/core/04-channel/keeper/grpc_query.go#L85) making the node hand and disconnect from peers.

Unlike most chains dymension testnet has a lot of open channels and relayer working and on top of that the relayers were asking for all channels frequently without limited pagination.

Though fixing the relayer call may help but it still leaves an opening for an external attack as we can't have a trivial query which isn't being called in an unusal number (i.e silk nodes says the number of calls is much less than the quota) , take the node down. 

IMO we should do the following:
1. Query manually the endpoint with a unlimited pagination and see how it effects the node.
2. Report/open an issue to the IBC team in case it does cause unexpected behavior with the consequences.

**Comment by omritoptix** [comment]
@ItayLevyOfficial can you please write a summary of the conclusion and close it?

**Comment by ItayLevyOfficial** [comment]
I ran a full node synchronized with Froopyland and executed the connectionChannels query from 1,000 processes simultaneously using connection-1008. The node managed it effectively. However, the node iterates over all the channels for every query, which is highly inefficient.
